#!/bin/bash

function createSupplierOrg() {
    infoln "Enrolling the CA admin"
    mkdir -p organizations/peerOrganizations/supplier.medtrack.com

    export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/supplier.medtrack.com/

    set -x
    fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-supplier --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
    { set +x; } 2>/dev/null

    echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-supplier.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-supplier.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-supplier.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-supplier.pem
    OrganizationalUnitIdentifier: orderer' >"${PWD}/organizations/peerOrganizations/supplier.medtrack.com/msp/config.yaml"

    # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

    # Copy suppier's CA cert to supplier's /msp/tlscacerts directory (for use in the channel MSP definition)
    mkdir -p "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/msp/tlscacerts"
    cp "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem" "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/msp/tlscacerts/ca.crt"

    # Copy supplier's CA cert to supplier's /tlsca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/tlsca"
    cp "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem" "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/tlsca/tlsca.supplier.medtrack.com-cert.pem"

    # Copy supplier's CA cert to supplier's /ca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/ca"
    cp "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem" "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/ca/ca.supplier.medtrack.com-cert.pem"

    infoln "Registering peer0"
    set -x
    fabric-ca-client register --caname ca-supplier --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering user"
    set -x
    fabric-ca-client register --caname ca-supplier --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering the org admin"
    set -x
    fabric-ca-client register --caname ca-supplier --id.name supplieradmin --id.secret supplieradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Generating the peer0 msp"
    set -x
    fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-supplier -M "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/peers/peer0.supplier.medtrack.com/msp" --csr.hosts peer0.supplier.medtrack.com --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/peers/peer0.supplier.medtrack.com/msp/config.yaml"

    infoln "Generating the peer0-tls certificates"
    set -x
    fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-supplier -M "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/peers/peer0.supplier.medtrack.com/tls" --enrollment.profile tls --csr.hosts peer0.supplier.medtrack.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
    cp "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/peers/peer0.supplier.medtrack.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/peers/peer0.supplier.medtrack.com/tls/ca.crt"
    cp "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/peers/peer0.supplier.medtrack.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/peers/peer0.supplier.medtrack.com/tls/server.crt"
    cp "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/peers/peer0.supplier.medtrack.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/peers/peer0.supplier.medtrack.com/tls/server.key"

    infoln "Generating the user msp"
    set -x
    fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-supplier -M "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/users/User1@supplier.medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/users/User1@supplier.medtrack.com/msp/config.yaml"

    infoln "Generating the org admin msp"
    set -x
    fabric-ca-client enroll -u https://supplieradmin:supplieradminpw@localhost:7054 --caname ca-supplier -M "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/users/Admin@supplier.medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/supplier.medtrack.com/users/Admin@supplier.medtrack.com/msp/config.yaml"
}

function createManufacturerOrg() {
    infoln "Enrolling the CA admin"
    mkdir -p organizations/peerOrganizations/manufacturer.medtrack.com/

    export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/

    set -x
    fabric-ca-client enroll -u https://admin:adminpw@localhost:7073 --caname ca-manufacturer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
    { set +x; } 2>/dev/null

    echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7073-ca-manufacturer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7073-ca-manufacturer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7073-ca-manufacturer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7073-ca-manufacturer.pem
    OrganizationalUnitIdentifier: orderer' >"${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/msp/config.yaml"

    # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

    # Copy manufacturer's CA cert to manufacturer's /msp/tlscacerts directory (for use in the channel MSP definition)
    mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/msp/tlscacerts"
    cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/msp/tlscacerts/ca.crt"

    # Copy manufacturer's CA cert to manufacturer's /tlsca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/tlsca"
    cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/tlsca/tlsca.manufacturer.medtrack.com-cert.pem"

    # Copy manufacturer's CA cert to manufacturer's /ca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/ca"
    cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/ca/ca.manufacturer.medtrack.com-cert.pem"

    infoln "Registering peer0"
    set -x
    fabric-ca-client register --caname ca-manufacturer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering user"
    set -x
    fabric-ca-client register --caname ca-manufacturer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering the org admin"
    set -x
    fabric-ca-client register --caname ca-manufacturer --id.name manufactureradmin --id.secret manufactureradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Generating the peer0 msp"
    set -x
    fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7073 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/peers/peer0.manufacturer.medtrack.com/msp" --csr.hosts peer0.manufacturer.medtrack.com --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/peers/peer0.manufacturer.medtrack.com/msp/config.yaml"

    infoln "Generating the peer0-tls certificates"
    set -x
    fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7073 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/peers/peer0.manufacturer.medtrack.com/tls" --enrollment.profile tls --csr.hosts peer0.manufacturer.medtrack.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
    cp "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/peers/peer0.manufacturer.medtrack.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/peers/peer0.manufacturer.medtrack.com/tls/ca.crt"
    cp "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/peers/peer0.manufacturer.medtrack.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/peers/peer0.manufacturer.medtrack.com/tls/server.crt"
    cp "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/peers/peer0.manufacturer.medtrack.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/peers/peer0.manufacturer.medtrack.com/tls/server.key"

    infoln "Generating the user msp"
    set -x
    fabric-ca-client enroll -u https://user1:user1pw@localhost:7073 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/users/User1@manufacturer.medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/users/User1@manufacturer.medtrack.com/msp/config.yaml"

    infoln "Generating the org admin msp"
    set -x
    fabric-ca-client enroll -u https://manufactureradmin:manufactureradminpw@localhost:7073 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/users/Admin@manufacturer.medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.medtrack.com/users/Admin@manufacturer.medtrack.com/msp/config.yaml"
}

function createDistributorOrg() {
    infoln "Enrolling the CA admin"
    mkdir -p organizations/peerOrganizations/distributor.medtrack.com/

    export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/distributor.medtrack.com/

    set -x
    fabric-ca-client enroll -u https://admin:adminpw@localhost:7096 --caname ca-distributor --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
    { set +x; } 2>/dev/null

    echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7096-ca-distributor.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7096-ca-distributor.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7096-ca-distributor.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7096-ca-distributor.pem
    OrganizationalUnitIdentifier: orderer' >"${PWD}/organizations/peerOrganizations/distributor.medtrack.com/msp/config.yaml"

    # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

    # Copy distributor's CA cert to distributor's /msp/tlscacerts directory (for use in the channel MSP definition)
    mkdir -p "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/msp/tlscacerts"
    cp "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/msp/tlscacerts/ca.crt"

    # Copy distributor's CA cert to distributor's /tlsca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/tlsca"
    cp "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/tlsca/tlsca.distributor.medtrack.com-cert.pem"

    # Copy distributor's CA cert to distributor's /ca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/ca"
    cp "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/ca/ca.distributor.medtrack.com-cert.pem"

    infoln "Registering peer0"
    set -x
    fabric-ca-client register --caname ca-distributor --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering user"
    set -x
    fabric-ca-client register --caname ca-distributor --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering the org admin"
    set -x
    fabric-ca-client register --caname ca-distributor --id.name distributoradmin --id.secret distributoradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Generating the peer0 msp"
    set -x
    fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7096 --caname ca-distributor -M "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/peers/peer0.distributor.medtrack.com/msp" --csr.hosts peer0.distributor.medtrack.com --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/peers/peer0.distributor.medtrack.com/msp/config.yaml"

    infoln "Generating the peer0-tls certificates"
    set -x
    fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7096 --caname ca-distributor -M "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/peers/peer0.distributor.medtrack.com/tls" --enrollment.profile tls --csr.hosts peer0.distributor.medtrack.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
    cp "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/peers/peer0.distributor.medtrack.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/peers/peer0.distributor.medtrack.com/tls/ca.crt"
    cp "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/peers/peer0.distributor.medtrack.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/peers/peer0.distributor.medtrack.com/tls/server.crt"
    cp "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/peers/peer0.distributor.medtrack.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/peers/peer0.distributor.medtrack.com/tls/server.key"

    infoln "Generating the user msp"
    set -x
    fabric-ca-client enroll -u https://user1:user1pw@localhost:7096 --caname ca-distributor -M "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/users/User1@distributor.medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/users/User1@distributor.medtrack.com/msp/config.yaml"

    infoln "Generating the org admin msp"
    set -x
    fabric-ca-client enroll -u https://distributoradmin:distributoradminpw@localhost:7096 --caname ca-distributor -M "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/users/Admin@distributor.medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/distributor.medtrack.com/users/Admin@distributor.medtrack.com/msp/config.yaml"
}

function createWholesalerOrg() {
    infoln "Enrolling the CA admin"
    mkdir -p organizations/peerOrganizations/wholesaler.medtrack.com/

    export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/

    set -x
    fabric-ca-client enroll -u https://admin:adminpw@localhost:8023 --caname ca-wholesaler --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
    { set +x; } 2>/dev/null

    echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8023-ca-wholesaler.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8023-ca-wholesaler.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8023-ca-wholesaler.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8023-ca-wholesaler.pem
    OrganizationalUnitIdentifier: orderer' >"${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/msp/config.yaml"

    # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

    # Copy wholesaler's CA cert to wholesaler's /msp/tlscacerts directory (for use in the channel MSP definition)
    mkdir -p "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/msp/tlscacerts"
    cp "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem" "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/msp/tlscacerts/ca.crt"

    # Copy wholesaler's CA cert to wholesaler's /tlsca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/tlsca"
    cp "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem" "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/tlsca/tlsca.wholesaler.medtrack.com-cert.pem"

    # Copy wholesaler's CA cert to wholesaler's /ca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/ca"
    cp "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem" "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/ca/ca.wholesaler.medtrack.com-cert.pem"

    infoln "Registering peer0"
    set -x
    fabric-ca-client register --caname ca-wholesaler --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering user"
    set -x
    fabric-ca-client register --caname ca-wholesaler --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering the org admin"
    set -x
    fabric-ca-client register --caname ca-wholesaler --id.name wholesaleradmin --id.secret wholesaleradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Generating the peer0 msp"
    set -x
    fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8023 --caname ca-wholesaler -M "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/peers/peer0.wholesaler.medtrack.com/msp" --csr.hosts peer0.wholesaler.medtrack.com --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/peers/peer0.wholesaler.medtrack.com/msp/config.yaml"

    infoln "Generating the peer0-tls certificates"
    set -x
    fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8023 --caname ca-wholesaler -M "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/peers/peer0.wholesaler.medtrack.com/tls" --enrollment.profile tls --csr.hosts peer0.wholesaler.medtrack.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
    cp "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/peers/peer0.wholesaler.medtrack.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/peers/peer0.wholesaler.medtrack.com/tls/ca.crt"
    cp "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/peers/peer0.wholesaler.medtrack.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/peers/peer0.wholesaler.medtrack.com/tls/server.crt"
    cp "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/peers/peer0.wholesaler.medtrack.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/peers/peer0.wholesaler.medtrack.com/tls/server.key"

    infoln "Generating the user msp"
    set -x
    fabric-ca-client enroll -u https://user1:user1pw@localhost:8023 --caname ca-wholesaler -M "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/users/User1@wholesaler.medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/users/User1@wholesaler.medtrack.com/msp/config.yaml"

    infoln "Generating the org admin msp"
    set -x
    fabric-ca-client enroll -u https://wholesaleradmin:wholesaleradminpw@localhost:8023 --caname ca-wholesaler -M "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/users/Admin@wholesaler.medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/wholesaler.medtrack.com/users/Admin@wholesaler.medtrack.com/msp/config.yaml"
}

function createRetailerOrg() {
    infoln "Enrolling the CA admin"
    mkdir -p organizations/peerOrganizations/retailer.medtrack.com/

    export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/retailer.medtrack.com/

    set -x
    fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-retailer --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
    { set +x; } 2>/dev/null

    echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-retailer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-retailer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-retailer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-retailer.pem
    OrganizationalUnitIdentifier: orderer' >"${PWD}/organizations/peerOrganizations/retailer.medtrack.com/msp/config.yaml"

    # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

    # Copy retailer's CA cert to retailer's /msp/tlscacerts directory (for use in the channel MSP definition)
    mkdir -p "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/msp/tlscacerts"
    cp "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/msp/tlscacerts/ca.crt"

    # Copy retailer's CA cert to retailer's /tlsca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/tlsca"
    cp "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/tlsca/tlsca.retailer.medtrack.com-cert.pem"

    # Copy retailer's CA cert to retailer's /ca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/ca"
    cp "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/ca/ca.retailer.medtrack.com-cert.pem"

    infoln "Registering peer0"
    set -x
    fabric-ca-client register --caname ca-retailer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering user"
    set -x
    fabric-ca-client register --caname ca-retailer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering the org admin"
    set -x
    fabric-ca-client register --caname ca-retailer --id.name retaileradmin --id.secret retaileradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Generating the peer0 msp"
    set -x
    fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/peers/peer0.retailer.medtrack.com/msp" --csr.hosts peer0.retailer.medtrack.com --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/peers/peer0.retailer.medtrack.com/msp/config.yaml"

    infoln "Generating the peer0-tls certificates"
    set -x
    fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/peers/peer0.retailer.medtrack.com/tls" --enrollment.profile tls --csr.hosts peer0.retailer.medtrack.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
    cp "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/peers/peer0.retailer.medtrack.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/peers/peer0.retailer.medtrack.com/tls/ca.crt"
    cp "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/peers/peer0.retailer.medtrack.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/peers/peer0.retailer.medtrack.com/tls/server.crt"
    cp "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/peers/peer0.retailer.medtrack.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/peers/peer0.retailer.medtrack.com/tls/server.key"

    infoln "Generating the user msp"
    set -x
    fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/users/User1@retailer.medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/users/User1@retailer.medtrack.com/msp/config.yaml"

    infoln "Generating the org admin msp"
    set -x
    fabric-ca-client enroll -u https://retaileradmin:retaileradminpw@localhost:8054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/users/Admin@retailer.medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/retailer.medtrack.com/users/Admin@retailer.medtrack.com/msp/config.yaml"
}

function createConsumerOrg() {
    infoln "Enrolling the CA admin"
    mkdir -p organizations/peerOrganizations/consumer.medtrack.com/

    export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/consumer.medtrack.com/

    set -x
    fabric-ca-client enroll -u https://admin:adminpw@localhost:8096 --caname ca-consumer --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
    { set +x; } 2>/dev/null

    echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8096-ca-consumer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8096-ca-consumer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8096-ca-consumer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8096-ca-consumer.pem
    OrganizationalUnitIdentifier: orderer' >"${PWD}/organizations/peerOrganizations/consumer.medtrack.com/msp/config.yaml"

    # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

    # Copy consumer's CA cert to consumer's /msp/tlscacerts directory (for use in the channel MSP definition)
    mkdir -p "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/msp/tlscacerts"
    cp "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/msp/tlscacerts/ca.crt"

    # Copy consumer's CA cert to consumer's /tlsca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/tlsca"
    cp "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/tlsca/tlsca.consumer.medtrack.com-cert.pem"

    # Copy consumer's CA cert to consumer's /ca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/ca"
    cp "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/ca/ca.consumer.medtrack.com-cert.pem"

    infoln "Registering peer0"
    set -x
    fabric-ca-client register --caname ca-consumer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering user"
    set -x
    fabric-ca-client register --caname ca-consumer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering the org admin"
    set -x
    fabric-ca-client register --caname ca-consumer --id.name consumeradmin --id.secret consumeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Generating the peer0 msp"
    set -x
    fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8096 --caname ca-consumer -M "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/peers/peer0.consumer.medtrack.com/msp" --csr.hosts peer0.consumer.medtrack.com --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/peers/peer0.consumer.medtrack.com/msp/config.yaml"

    infoln "Generating the peer0-tls certificates"
    set -x
    fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8096 --caname ca-consumer -M "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/peers/peer0.consumer.medtrack.com/tls" --enrollment.profile tls --csr.hosts peer0.consumer.medtrack.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
    cp "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/peers/peer0.consumer.medtrack.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/peers/peer0.consumer.medtrack.com/tls/ca.crt"
    cp "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/peers/peer0.consumer.medtrack.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/peers/peer0.consumer.medtrack.com/tls/server.crt"
    cp "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/peers/peer0.consumer.medtrack.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/peers/peer0.consumer.medtrack.com/tls/server.key"

    infoln "Generating the user msp"
    set -x
    fabric-ca-client enroll -u https://user1:user1pw@localhost:8096 --caname ca-consumer -M "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/users/User1@consumer.medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/users/User1@consumer.medtrack.com/msp/config.yaml"

    infoln "Generating the org admin msp"
    set -x
    fabric-ca-client enroll -u https://consumeradmin:consumeradminpw@localhost:8096 --caname ca-consumer -M "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/users/Admin@consumer.medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/consumer.medtrack.com/users/Admin@consumer.medtrack.com/msp/config.yaml"
}

function createOrderer() {
    infoln "Enrolling the CA admin"
    mkdir -p organizations/ordererOrganizations/medtrack.com

    export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/medtrack.com

    set -x
    fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' >"${PWD}/organizations/ordererOrganizations/medtrack.com/msp/config.yaml"

    # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

    # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
    mkdir -p "${PWD}/organizations/ordererOrganizations/medtrack.com/msp/tlscacerts"
    cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/medtrack.com/msp/tlscacerts/tlsca.medtrack.com-cert.pem"

    # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
    mkdir -p "${PWD}/organizations/ordererOrganizations/medtrack.com/tlsca"
    cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/medtrack.com/tlsca/tlsca.medtrack.com-cert.pem"

    infoln "Registering orderer"
    set -x
    fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Registering the orderer admin"
    set -x
    fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Generating the orderer msp"
    set -x
    fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/medtrack.com/orderers/orderer.medtrack.com/msp" --csr.hosts orderer.medtrack.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/ordererOrganizations/medtrack.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/medtrack.com/orderers/orderer.medtrack.com/msp/config.yaml"

    infoln "Generating the orderer-tls certificates"
    set -x
    fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/medtrack.com/orderers/orderer.medtrack.com/tls" --enrollment.profile tls --csr.hosts orderer.medtrack.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
    cp "${PWD}/organizations/ordererOrganizations/medtrack.com/orderers/orderer.medtrack.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/medtrack.com/orderers/orderer.medtrack.com/tls/ca.crt"
    cp "${PWD}/organizations/ordererOrganizations/medtrack.com/orderers/orderer.medtrack.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/medtrack.com/orderers/orderer.medtrack.com/tls/server.crt"
    cp "${PWD}/organizations/ordererOrganizations/medtrack.com/orderers/orderer.medtrack.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/medtrack.com/orderers/orderer.medtrack.com/tls/server.key"

    # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
    mkdir -p "${PWD}/organizations/ordererOrganizations/medtrack.com/orderers/orderer.medtrack.com/msp/tlscacerts"
    cp "${PWD}/organizations/ordererOrganizations/medtrack.com/orderers/orderer.medtrack.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/medtrack.com/orderers/orderer.medtrack.com/msp/tlscacerts/tlsca.medtrack.com-cert.pem"

    infoln "Generating the admin msp"
    set -x
    fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/medtrack.com/users/Admin@medtrack.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/ordererOrganizations/medtrack.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/medtrack.com/users/Admin@medtrack.com/msp/config.yaml"
}
